### ISSUE TITLE
Meaning of scores in results

### ISSUE THREAD

**Issue by IwanParf** [pFindStudio/pLink2#10]
I would like to better understand the output of plink 2.
It has now an E-value (smaller = more confident) and a score (bigger = more confident). If I search some data files with plink 2, for which I have results with plink 1, It looks like the E-value is quite similar to the score in plink 1, but the plink 2 score does not really correlate with the plink 1 score anymore, so what does it tell you exactly? Is it the prime measure for FDR calculation in plink 2 and is it replaced by the E- value if one activates its calculation before the search? How can I interpret Alpha_Matched, Beta_Matched, Alpha_Evalue, and Beta_Evalue?

Thank you in advance!

**Comment by 01joy** [comment]
Hi IwanParf,

Here are the meanings of the output in pLink2:

1. Score, the pLink2 score, the smaller the more confident, it is the prime measure for FDR calculation.
2. Evalue, evalue calculated only for filtered PSM by FDR, the smaller the more confident, it is similar to the score in pLink1, pLink2 won't calculate it by default, which results in all evalue scores are 1.
3. Alpha_Matched and Beta_Matched are matched ion number for alpha and beta peptide respectively.
4. Alpha_Evalue and Beta_Evalue are evalues calculated for alpha and beta peptide respectively. pLink2 won't calculate it by default, which results in all evalue scores are 1.

The Score is the best one to decide a good PSM among these 'scores'.

**Comment by sulezinha** [comment]
Thank you for the explanation. I have realized that some values in both Alpha_Matched and Beta_Matched have values like 1.5, 0.5. Why does counting include 0.5? I thought these values were counting matched b and y ions on the experimental spectra.

**Comment by 01joy** [comment]
Dear @sulezinha ,

Suppose **Alpha_Num** and **Beta_Num** mean the number of peaks matched to alpha peptide and beta peptide respectively. But some peaks may match both alpha and beta peptide, suppose there are **Share_Num** shared peaks. Then, the final **Alpha_Matched=Alpha_Num-0.5*Share_Num**, **Beta_Matched=Beta_Num-0.5*Share_Num**. As a result, 1.5 or 0.5 may appear.
