### ISSUE TITLE
pLink (and pParse) not working on Astral data

### ISSUE THREAD

**Issue by amaralbc** [pFindStudio/pLink2#104]
Hello,

I'm trying to run some Thermo Astral data on pLink, but I'm getting an error when searching using the .raw files. I have MS File Reader installed and I'm able to process orbitrap data (from an Eclipse and from a QExactive) with no problems at all.
The error I'm getting is this:

![pLink_CrashLog_AstralData](https://github.com/pFindStudio/pLink2/assets/69264262/f7c50d8b-6380-40be-ae20-5004a0b2ef1b)

It happens in the beginning when extracting the data. If I click OK, it tries to resume and says the engine is ready to search. However, it gets stuck in the start search line and it doesn't go through:

[pLink] Start searching C:\Users\Lab\Desktop\Processing\pLink\AstralTestingPhoX.raw, Labeling None

It stays there for days and nothing happens. 
The same data file does work if I first convert it to MGF using ProteoWizard, but that means I lose intensity info.
Is there any workaround?

Thanks!

**Comment by amaralbc** [comment]
Just a quick add if that helps: I've tried to run pParse directly from cmd on the raw file, according to the instructions here: http://pfind.org/software/pParse/index.html

It generates the .ms1 and .ms2 files, however the .xtract file has a size of 0kb before throwing the same error as before with the "unhandled exception". This is the info I have on the terminal:

C:\Program Files\pLink\2.3.11\bin>pParse.exe -D C:\Users\Lab\Desktop\Processing\pLink\AstralTestingPhoX.raw

          *********************************************
         /       pParse2.0 (x64) from pFind Studio     \
        /        Email  :  pfind@ict.ac.cn              \
        \        Website:  http://pfind.ict.ac.cn       /
          *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files...
[pXtract] The software will expire in 01/01/2100
[pXtract] Begin to extract C:\Users\Lab\Desktop\Processing\pLink\AstralTestingPhoX.raw
[pXtract] pXtract tries to use MSFileReader
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 1002.03s. == == ==
[pParse] MS1list completes.
[pParse] Processing C:\Users\Lab\Desktop\Processing\pLink\AstralTestingPhoX.MS1
[pParse] Start spliting MS2...
[pParse] File 0: C:\Users\Lab\Desktop\Processing\pLink\AstralTestingPhoX_ID_0.ms2 complete!
[pParse] File 1: C:\Users\Lab\Desktop\Processing\pLink\AstralTestingPhoX_ID_1.ms2 complete!
[pParse] Loading MS1 and MS2 files...
[pParse] Loading MS1 Spectra Number: 6603

At this point the error pops up like before. If I click OK in the error pop-up, pParse just quits and cmd go back to waiting commands.

**Comment by NorthblueM** [comment]
Sorry for the delay in updating the spectra extraction plug-in, pXtract, and the precursor correction plug-in, pParse, within the current version of pLink to support Astral data. The format of Astral's data differs slightly from that of Orbitrap's. Rest assured, we are actively addressing this issue and plan to release a new version once internal testing is completed.

Indeed, MSconvert can be used to extract mgf before feeding it to pLink search for the time being, although the mgf extracted by MSConvert might lack mass correction and mixed spectra features compared to what pParse offers. I'm curious, are you looking for the intensity information of the precursor ions, or something else?

**Comment by michabirklbauer** [comment]
Hi,

any updates on this?

I can confirm that this is still an issue unfortunately, converting the astral RAW files to MGF beforehand works but using the RAW files directly in pLink 2 does not (same error as described above).

**Comment by NorthblueM** [comment]
pLink 3 is now available. Just need to download and install it again.

pLink3 supports cleavable cross-linkers (e.g., DSSO, DSBSO) and new instruments (e.g., Astral, timsTOF).

pLink3 GitHub Repository: https://github.com/pFindStudio/pLink3
[Download the latest release here](https://github.com/pFindStudio/pLink3/releases)

**Comment by NorthblueM** [comment]
@amaralbc If you still need a tool for extracting cross-linked peptide precursor intensity, please contact support@pfind.org. We are currently developing related tools.
