### ISSUE TITLE
Generation of a reverse database

### ISSUE THREAD

**Issue by IwanParf** [pFindStudio/pLink2#11]
Hello, this is maybe a minor and quite specific request:
I used to run plink searches with a custom decoy database, e.g. with more decoys than targets, or pseudo-reversed/shuffled sequences. For this, I just modified the "*_comb_rever.fasta" file and made it read-only. Plink 1 did not have a problem with that and simply used this modified fasta, but plink 2 is stopping at the decoy generation step and does not proceed. Would it be possible to modify plink 2 so that it does not stop during decoy generation if it is not allowed to write the comb_rever.fasta file? Or could it maybe skip that step if the comb_rever.fasta already exists?
Thank you in advance!

Iwan

**Comment by 01joy** [comment]
Hi IwanParf,

Thank you for using pLink2.

pLink2 generates reversed database automatically, it doesn't allow users to customize decoy database for now. We will consider your advice in the next version.
