### ISSUE TITLE
File number in .csv report file "Title" column

### ISSUE THREAD

**Issue by kallepult** [pFindStudio/pLink2#13]
Thanks for a great piece of software!

I would like to know how to figure out which peptide identifications in the .csv reports came from which of my input .mgf files. The names of my .mgf files do not seem to appear in the .csv reports, however, in the "Title" column is listed "FileXXX_SpectrumXXXX_scans:_XXXX", with the FileXXX having as many different numbers as the number of my .mgf input files.

As far as I can tell from the ".features.csv" files in the "tmps" folder, the order of the numbering of "FileXXX" follows the order of the files when they were loaded into pLink - is this correct? Maybe the original file name could be included in a future version of the software.

Thanks in advance!

Best regards,
Kasper

**Comment by kallepult** [comment]
I realised that I overlooked the FileID column in the .csv report file - I assume that this FileID corresponds to the order of the files when loading them into pLink.

**Comment by 01joy** [comment]
Hi kallepult,

Yes, the `FileID` in the .csv report file indicates the order of the files when loading them into pLink2.
