### ISSUE TITLE
searcher.exe has stopped working

### ISSUE THREAD

**Issue by IwanParf** [pFindStudio/pLink2#17]
Hello pLink developers,
my searches keep crashing for whatever reason in the middle of the search of 5 of 14 files. I search a complex sample against app. 500 proteins. Previously it worked with a database of app. 1000 proteins. I provide raw files from an QExactive HF-X. There is no error in the plink log, only the following windows problem details:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	searcher.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5a479990
  Fault Module Name:	libstdc++-6.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	521eede5
  Exception Code:	40000015
  Exception Offset:	000000000001b87b
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1031
  Additional Information 1:	0e0f
  Additional Information 2:	0e0fc6cf60ce9a1dcdda8b0de923e38b
  Additional Information 3:	2caf
  Additional Information 4:	2cafac43881c07e3842aa55a429dcdde

Plink itself seems to not notice a problem and keeps "running", but is not using any CPU anymore. I have to manually stop it.

Any idea?

Best regards,

Iwan

**Comment by 01joy** [comment]
Hi @IwanParf ,

Did you mean all first 4 files were successfully searched except the fifth one ? Could you provide me with the parameter file located in result folder and log file located in result folder/tmps/log.out so that I can know more about the crash?

**Comment by IwanParf** [comment]
it crashed after ...File5.pfd, so I assume it finished the 4 files before. Attached are the parameter file and the log file. I repeated the searches now several times (the attached one crashed during the 7th file) and it has no impact on how many process numbers I use.

[log_and_par.zip](https://github.com/pFindStudio/pLink2/files/1673979/log_and_par.zip)

**Comment by 01joy** [comment]
Hi @IwanParf , 

From your log file, I only know that it crashed at `Spectra preprocessing...` stage of 7th file `I_Parfentev_240118_Synapt_DSS_F23_HCDFT.pf2`, but it didn't report any more detailed info.

Could you try to run the 7th file `I_Parfentev_240118_Synapt_DSS_F23_HCDFT.pf2` alone,  if it crashes again, please send me the RAW file so that I can reproduce the problem and try to fix it.

By the way, it seems you are running pLink2 on non-english edition of Windows, the decimal point became comma in the configure file, `FDR = 0,01`, this bug has been fixed and we will release the new version in these days.

**Comment by IwanParf** [comment]
Hello 01Joy,
it also crashes, when running alone. Interestingly, searcher.exe first occupied all of my available RAM (~63 Gb) and then crashed. Can you recommend a fast way to share the raw file with you? It is app. 2.4 Gb.

**Comment by 01joy** [comment]
Hi @IwanParf ,

I'm confused why searcher.exe needed so many memory.

Please send me the RAW file and your parameter file by email: plink@ict.ac.cn, I will reanalyse it.

**Comment by 01joy** [comment]
Hi @IwanParf ,

We have found the problem, as there is a peak with negative m/z, pLink2 crashed. As the negative m/z is very rare and provides no information for identification, we will simply skip these peaks in the next version.

The new version 2.3.2 has fixed this bug, you can download it from pLink's homepage.

Thanks for your feedback.
