### ISSUE TITLE
DMTMM

### ISSUE THREAD

**Issue by ShenXipeng** [pFindStudio/pLink2#2]
Congratulations! you guys have done great works in the past and I hope you achieve greater success in the future.
Recommendation: a new crosslink reagent calld DMTMM developed by Ruedi Aebersold 2014 PNAS. was now gradually used by researchers. You can consider adding it to your program.

**Comment by 01joy** [comment]
Hi ShenXipeng,

Thanks for using pLink.

**Here is the tutorial for adding a new linker in pLink2:**

1. Click Options→Meta Data Configuration
2. Select Linkers tab
![image](https://user-images.githubusercontent.com/8603895/34522338-1ca7d29e-f0cd-11e7-8b6a-1c671cac7bf2.png)
3. Click Add, fill in linker information in the dialog
![image](https://user-images.githubusercontent.com/8603895/34522366-39c144b4-f0cd-11e7-850f-6068f99b4748.png)
4. Click Update and then Save
5. Close pConfig window, the new linker will appear in Linkers ListView
![image](https://user-images.githubusercontent.com/8603895/34522634-835bbcac-f0ce-11e7-89fd-67ec8d7d709d.png)

**Linker information needed:**

- Name: the name of the new linker.
- AlphaSites: the  first  cross-linked  amino  acid, parentheses  “(” and  “)”  denote  the  peptide  N  terminus  and  C  terminus,  respectively; square brackets “[“ and “]” denote the protein N terminus and C terminus, respectively.
- BetaSites: the  second cross-linked  amino  acid, “(”, “)”, “[“,  and “]”  denote the same as AlphaSites. 
- LinkerMass: monoisotopic  linker  mass  in  inter/loop links.
- MonoMass: monoisotopic linker mass in mono links.
- LinkerComposition: linker composition in inter/loop links.
- MonoComposition: linker composition in mono links. 
- LongMass: the longer mass in cleavable linker, 0 for uncleavable linker.
- ShortMass: the shorter mass in cleavable linker, 0 for uncleavable linker.

For parameter format, you can take BS3 as an example.

**Comment by ShenXipeng** [comment]
That's really help! Thanks a lot.
