### ISSUE TITLE
Unable to use pLink 2.3.0 with RAW files

### ISSUE THREAD

**Issue by mriffle** [pFindStudio/pLink2#20]
Hi, I'm running pLink 2.3.0 on Windows 10 and have the latest MSFileReader 3.1 SP4 installed from Thermo.

I am able to run pLink 2.3.0 with MGF files successfully. However, when I attempt to use a RAW file I get the following error output:

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract C:\Users\PLink User\Desktop\gTuSC\Q_2013_1010_RJ_07.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Exception>: MSFileReader should be 32/64 bit version corresponding to pFind.
[pParse] MS1list completes. 
[pParse] Processing Q_2013_1010_RJ_07.MS1 
[pParse] MS1 Or MS2 files not completely extracted! Q_2013_1010_RJ_07 
[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract C:\Users\PLink User\Desktop\gTuSC\Q_2013_1010_RJ_07.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Exception>: MSFileReader should be 32/64 bit version corresponding to pFind.

Please advise.

**Comment by 01joy** [comment]
Hi @mriffle ,

I'm sorry to tell you that pParse is **not** compatible with the latest MSFileReader 3.1 SP4. pLink 2 has been tested with **MS File Reader 3.1 SP2 or below**. Please see https://github.com/pFindStudio/pLink2/wiki/FAQ#how-to-install-msfilereader for more details about installing MSFileReader.

**Comment by mriffle** [comment]
Thank you for your response, I will try to find the older version and give that a try.

**Comment by armadillocommander** [comment]
You can find all versions of MSFileReader from the github of MSFileReader.py project.

**Comment by 01joy** [comment]
@armadillocommander Did you mean this repo: https://github.com/frallain/MSFileReader-Python-bindings/tree/master/MSFileReader ?

**Comment by armadillocommander** [comment]
Yes, it has a collection of MSFileReader with different versions.

**Comment by 01joy** [comment]
@armadillocommander Great, thanks for your sharing.
