### ISSUE TITLE
MS2 Spectra Annotation cannot be displayed correctly in pLabel 2.4

### ISSUE THREAD

**Issue by armadillocommander** [pFindStudio/pLink2#21]
Hi,

When I tried to view the spectra of pLink 2.3 search result in pLabel 2.4, I found that part of the MS2 peak annotation cannot be displayed correctly, which was rendered as "Á" or "Â" (as shown in the attached spectra). 

![ex38_trypsin_glu-c_3-7_rep2 3749 3749 3 0 dta 2](https://user-images.githubusercontent.com/35280275/36507193-d9eeed86-170d-11e8-997c-41aff4768cf5.png)

My guess is that "Á" and "Â" denote each peptide cross-linked, respectively.I don't know what the letters or symbols they should be, but based on the spectra provided in the SI of the original paper (https://media.nature.com/original/nature-assets/nmeth/journal/v12/n4/extref/nmeth.3283-S1.pdf), I guess they should be α and β.

![capture](https://user-images.githubusercontent.com/35280275/36507059-687e9a84-170d-11e8-80e1-c501992cfe69.PNG)

Anyone has suggestion about the issue? Thanks!

**Comment by 01joy** [comment]
Hi @armadillocommander ,

Did it happen only with this RAW file or it always happens with any RAW files?

I guess it has something to do with encoding problem. What's your language of Windows?

Could you provide me with the *.plabel file and *.mgf file so that I can reproduce your problem.

Thanks for your feedback.

**Comment by armadillocommander** [comment]
It happens on all the raw files. I’m using Windows 10 English. I’ll send you the pLabel and .mgf soon.

**Comment by armadillocommander** [comment]
Hi,

The .mgf and corresponding cross-linked peptide .pLabel files are in the attached .zip file. One of the spectra rendered on my computer is shown below:

![ex38_trypsin_glu-c_2 _rep1 10172 10172 3 0 dta](https://user-images.githubusercontent.com/35280275/38057563-be40303e-3294-11e8-9330-4eec012b0855.png)


[Ex38_Trypsin_Glu-C_2+_rep1_HCDFT.zip](https://github.com/pFindStudio/pLink2/files/1857841/Ex38_Trypsin_Glu-C_2._rep1_HCDFT.zip)

**Comment by 01joy** [comment]
Hi,

I have loaded your plabel and mgf, it shows correctly in Windows 10 Chinese Edition, but the problem does exist in Windows 10 English Edition. We will fix this bug in the next days.

Thanks for your feedback.

**Comment by 01joy** [comment]
Hi @armadillocommander ,

After several days of debugging and testing, we have found the solution. As pLabel didn't use the Unicode character set, you have to set the language for non-Unicode programs as Chinese. Follow these steps:

1. Open **Control Panel** in Windows 10
2. Click **Change date, time, or number formats**
3. Click **Administrative** tab
4. Click **Change system locale...**
5. Find and select **Chinese (Simplified, China)**
6. Click **OK** and **Apply**
7. Restart Windows

Re-open pLabel, it will display α and β correctly. Note this won't change your Windows display language, but may affect some non-Unicode programs.

Thanks for your feedback!
