### ISSUE TITLE
DSSO long & short mass

### ISSUE THREAD

**Issue by talpa25** [pFindStudio/pLink2#22]
Dear developer,

just a quick question. Why did you in the characterisation of the DSSO crosslinker decided to go for the long mass 85.983 which includes the sulfur (C3 H2 S O) and not for the "real" long mass 103.9432 which contains the oxygen bound to the sulfur as well (C3 H4 O2 S)? Is that on purpose and if so, why?

Best
Roman

**Comment by 01joy** [comment]
Dear @talpa25 ,

Yes, we did it on purpose, as is suggested in the paper of DSSO ([Development of a Novel Cross-linking Strategy for Fast and Accurate Identification of Cross-linked Peptides of Protein Complexes](http://www.mcponline.org/content/10/1/M110.002212)). 

It said:

![image](https://user-images.githubusercontent.com/8603895/36956251-49ac47dc-2068-11e8-82ab-ca3689c92a58.png)

You can read the paper for more details.
