### ISSUE TITLE
Multiple Enzyme Search

### ISSUE THREAD

**Issue by xLinkKnight** [pFindStudio/pLink2#23]
Is it possible to implement a way to search using two digestion enzymes with different cleavage site specificities? Currently we employ a combination of trypsin with other proteases because trypsin along will not yield suitable peptides for analysis. We have tried to alter the enzyme file to include an entry that combines the two cleavage sites, however this is not exactly correct because the enzymes differ in what adjacent resides prevent cleavage. The ability to search using a theoretical digest with two enzymes would greatly help our efforts.

**Comment by 01joy** [comment]
Hi @xLinkKnight ,

pLink2 support multiple enzymes search, you can add your own enzyme in pConfig->Enzymes. Combine the cleavage sites of multiple enzymes into one enzyme, you can take the Glu-C.Trypsin as an example, which is the combination of enzyme Glu-C and Trypsin.

![image](https://user-images.githubusercontent.com/8603895/36945486-c5326afa-1fe9-11e8-8969-42ce7245e96d.png)
