### ISSUE TITLE
pLink will not perform MS-cleavable search

### ISSUE THREAD

**Issue by talpa25** [pFindStudio/pLink2#24]
Dear developers,

so far i'm very happy with your software. Unfortunately, now i've tried to run DSSO searches, pLink pretends to start searching: "[pLink] Start searching D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_2M_DSSO1_CID-ETD.mgf, Labeling None" but it hangs up at this stage.

I'm running pLink2 on a Windows 8.1 64 Bit system with english language settings. "Normal" crosslinker search are well performed.

Do you have any clue?

Best
Roman

**Comment by talpa25** [comment]
Hey,

i had a look in the folder and the file does not exist. Is the file name too long? 

Here is the log from pParse:

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_2M_DSSO1.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 98.746s. == == ==
[pParse] MS1list completes. 
[pParse] Processing 20180122_TOC_2M_DSSO1.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 11208 
[pParse] Loading MS2 Spectra Number: 2457 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 5242 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 110 seconds. == == == =  

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_2M_DSSO2.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 103.531s. == == ==
[pParse] MS1list completes. 
[pParse] Processing 20180122_TOC_2M_DSSO2.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 11327 
[pParse] Loading MS2 Spectra Number: 1989 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 3864 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 113 seconds. == == == =  

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_250mM_DSSO_1.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 106.411s. == == ==
[pParse] MS1list completes. 
[pParse] Processing 20180122_TOC_250mM_DSSO_1.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 9957 
[pParse] Loading MS2 Spectra Number: 6445 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 12185 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 121 seconds. == == == =  

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_250mM_DSSO_2.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 89.6s. == == ==
[pParse] MS1list completes. 
[pParse] Processing 20180122_TOC_250mM_DSSO_2.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 9993 
[pParse] Loading MS2 Spectra Number: 6399 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 11808 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 104 seconds. == == == =  

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract D:\20180108_TOC_XL_mE_XL_MS\20180108_TOC_DSSO1_75mM.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 121.942s. == == ==
[pParse] MS1list completes. 
[pParse] Processing 20180108_TOC_DSSO1_75mM.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 11756 
[pParse] Loading MS2 Spectra Number: 3660 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 4824 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 131 seconds. == == == =  

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract D:\20180108_TOC_XL_mE_XL_MS\20180108_TOC_DSSO2_75mM.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 122.153s. == == ==
[pParse] MS1list completes. 
[pParse] Processing 20180108_TOC_DSSO2_75mM.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 11721 
[pParse] Loading MS2 Spectra Number: 3846 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 4981 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 131 seconds. == == == =  
D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_2M_DSSO1_CIDFT.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_2M_DSSO1_CID-ETD.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_2M_DSSO2_CIDFT.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_2M_DSSO2_CID-ETD.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_250mM_DSSO_1_CIDFT.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_250mM_DSSO_1_CID-ETD.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_250mM_DSSO_2_CIDFT.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_250mM_DSSO_2_CID-ETD.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180108_TOC_DSSO1_75mM_CIDFT.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180108_TOC_DSSO1_75mM_CID-ETD.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180108_TOC_DSSO2_75mM_CIDFT.mgf
D:\20180108_TOC_XL_mE_XL_MS\20180108_TOC_DSSO2_75mM_CID-ETD.mgf
[pLink] Welcome to use pLink v2.3.1, it will be expired on 20190101
[pLink] Search Engine initializing...
[pLink] Generating reverse database...
[pLink] Search identifier: NNAZB
[pLink] Search Engine is ready to search.

[pLink] Start searching D:\20180108_TOC_XL_mE_XL_MS\20180122_2nd_plate\20180122_TOC_2M_DSSO1_CID-ETD.mgf, Labeling None

Would could be the possible error?

Best

**Comment by talpa25** [comment]
Actually, what i do have, and what corresponds to the time stamp are files like:
20180108_TOC_DSSO1_75mM_HCDFT.mgf

**Comment by 01joy** [comment]
Hi @talpa25 ,

The current version of pLink2 only supports CID+ETD mode of cleavage cross-linkers, which was introduced in XlinkX1.0 paper (https://www.nature.com/articles/nmeth.3603).

If the Raw file matches to this mode, after pParse, two files, _CIDFT.mgf and _ETDFT.mgf will be generated, then, pLink2 will combine these two to one _CID-ETD.mgf.

If not, pLink2 doesn't support for now. 

![image](https://user-images.githubusercontent.com/8603895/37194230-379c9680-23a8-11e8-94a5-e6351de7d97e.png)

![image](https://user-images.githubusercontent.com/8603895/37194181-0313942c-23a8-11e8-9d22-b80ec3a82e2a.png)

**Comment by talpa25** [comment]
Oh. good to know. Since the XlinkX Algorithm supports HCD only as well itought it would be possible here...

Do you have plans to extend pLink to this feature?

Best

**Comment by 01joy** [comment]
Sorry, we are not sure as we have many other things to do in this year.
