### ISSUE TITLE
MS cleavable cross-linking

### ISSUE THREAD

**Issue by KamalMandal** [pFindStudio/pLink2#29]
Does pLink2 support MS-Cleavable cross linker?
Is Leiker_clv MS-cleavable (listed in the cross linker list of plink2)?

**Comment by 01joy** [comment]
Hi @KamalMandal ,

pLink2 supports DSSO, the MS-cleavable cross-linker used in Liu F, Rijkers D T S, Post H, et al. Proteome-wide profiling of protein assemblies by cross-linking mass spectrometry[J]. Nature methods, 2015, 12(12): 1179.

For more about DSSO supported in pLink2, please see #22 and #24 .

The Leiker_clv is not an MS-cleavable cross-linker. It is a trifunctional cross-linker. It is a lysine-targeted enrichable cross-linker containing a biotin tag for affinity purification, a chemical cleavage site to separate cross-linked peptides away from biotin after enrichment, and a spacer arm that can be labeled with stable isotopes for quantitation. 

The clv in Leiker_clv means the biotin can be cleaved out. For more details about Leiker, please see Tan D, Li Q, Zhang M J, et al. Trifunctional cross-linker for mapping protein-protein interaction networks and comparing protein conformational states[J]. Elife, 2016, 5.

**Comment by KamalMandal** [comment]
Thanks a lot @01joy  for your help.
Is there any plan to introduce MS cleavable feature in Leiker_clv in near future? I think that would decrease the computational complexity drastically? Is there any commercial organization from where Leiker_clv can be procured?

**Comment by armadillocommander** [comment]
@01joy

I talked with them yesterday, I’ll try to ask them if I meet with them tomorrow.

**Comment by 01joy** [comment]
Hi @armadillocommander ,

Thank you for your contributions to this community.

**Comment by 01joy** [comment]
Hi all,

You can purchase Leiker cross-linker from here: http://www.jkchemical.com/en/products/A012138035.html.
