### ISSUE TITLE
Phosphopeptide dimers.

### ISSUE THREAD

**Issue by PhosPhopeptides** [pFindStudio/pLink2#3]
Can pLink be used to identify phosphopeptide dimers? How does one go about configuring the linker?

**Comment by 01joy** [comment]
Hi PhosPhopeptides,

You can follow the step-by-step tutorial  (#2 ) to add a new linker in pLink2.

**Comment by PhosPhopeptides** [comment]
I appear to be getting the basics wrong, as when I run the programme I get the response below....


	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract W:\Identifications\Colin\2017-12\CK_2017-12-20_1D_Auto_-C.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Exception>: MSFileReader should be 32/64 bit version corresponding to pFind.
[pParse] MS1list completes. 
[pParse] Processing CK_2017-12-20_1D_Auto_-C.MS1 
[pParse] MS1 Or MS2 files not completely extracted! CK_2017-12-20_1D_Auto_-C 
[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract W:\Identifications\Colin\2017-12\CK_2017-12-20_1D_Auto_-C.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Exception>: MSFileReader should be 32/64 bit version corresponding to pFind.

[pParse] 
Dear User:
 pParse.exe failed to open W:\Identifications\Colin\2017-12\CK_2017-12-20_1D_Auto_-C.ms2, this file does not exist any more!
 
[pParse] pParse has encountered a problem and will exit. Retry with correct parameters.
Contact pparse@ict.ac.cn for help. 
[pLink] Welcome to use pLink v2.2.1649, it will be expired on 20190101
[pLink] Search Engine initializing...

**Comment by 01joy** [comment]
Hi PhosPhopeptides,

According to your log **"[pXtract] : MSFileReader should be 32/64 bit version corresponding to pFind."**. It seems your MSFileReader hadn't been installed correctly. You should install MSFileReader both 32 and 64 bit version. 

You can follow [the MaxQuant docs](http://www.coxdocs.org/doku.php?id=maxquant:common:download_and_installation#msfilereader) to install MSFileReader, **be sure to install both 32 and 64 bit version**.

If everything is installed correctly, the log should be like this:

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract E:\TestData\raw\d\RD_pH_8point3_step5.raw
**[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%**
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 27.088s. == == ==
[pParse] MS1list completes. 
[pParse] Processing RD_pH_8point3_step5.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 2143 
[pParse] Loading MS2 Spectra Number: 6391 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 17218 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 48 seconds. == == == =  
[pLink] Welcome to use pLink v2.2.1649, it will be expired on 20190101
[pLink] Search Engine initializing...
