### ISSUE TITLE
pLink2 does not start

### ISSUE THREAD

**Issue by TLee7** [pFindStudio/pLink2#30]
Hi,

I am trying to use pLink2 to analyze some of my data.
But, pLink does not start: When I double click pLink2, It tries to open a window but closed down.
pLabel and pConfig had no problem.

Do you have any idea?

I am using windows 10 enterprise, Xcalibur 2.2, .NET framework version 4.7

Thanks,

**Comment by armadillocommander** [comment]
Hi, 
You can try to update the pLink2 to newest version released last week, I had the same issue and it’s fixed in new version.

**Comment by TLee7** [comment]
It works.
Thank you!
