### ISSUE TITLE
pLink 2 gets stuck on "initializing search engines" 

### ISSUE THREAD

**Issue by mgold2** [pFindStudio/pLink2#31]
I'm trying to do a cross-linking experiment with BS(PEG)5 of CMG2 protein and PA. I also have formaldehyde tagging involved. I have added the new cross-linker and the PTMs associated with this. I have also downloaded the .FASTA file from UNIPROT.org. When trying to run pLink2, it seams to get stuck on "initializing search engine". I have left it for several days and tried using .RAW and .MGF files. It has yet to get past that phase. 

(https://user-images.githubusercontent.com/40864982/42332638-c5508d80-8035-11e8-983d-e75e2fd1ccff.png)

**Comment by IwanParf** [comment]
Weird guess: you specified a nonspecific digestion, i.e. cleavage before/after every amino acid, with 3 missed cleavages, i.e. resulting theoretical peptides are between one and four amino acids, but you specified a minimum peptide length of 6. So the search engine basically cannot do anything. Can you try it with a number of missed cleavages bigger than the minimum peptide length, e.g. 10?

Best,

Iwan

**Comment by armadillocommander** [comment]
Check the log file in temp folder, it gives little more information.

**Comment by mgold2** [comment]
I tried changing that Iwan. It still got stuck on the same spot(no processor power was used). It only allowed me to change it to 5 missed cleavages. So I changed the enzyme to trypsin to see if the search would start; it still was stuck on "initializing search engine". I also tried lowering the peptide length and still no success. 
the log file keeps repeating that it is loading the different settings.
[log.out.txt](https://github.com/pFindStudio/pLink2/files/2167398/log.out.txt)

**Comment by mgold2** [comment]
[debug] Loading element settings...

[debug] Loading Quant settings...

[debug] Loading enzyme settings...

[debug] Loading amino acids settings...

[debug] Loading modification settings...


over and over again

**Comment by mgold2** [comment]
That worked 01joy. Thank you. I deleted the modifications from the modification.ini file. I then re-added them through the GUI of the software.

**Comment by 01joy** [comment]
@mgold2 That's right. Please always configure pLink2 through the GUI instead of editing the .ini file directly, because GUI has validity check.

**Comment by PhosPhopeptides** [comment]
Once you have made the errors in the Linkers how do you edit it. The pConfig won't allow me access.

**Comment by mgold2** [comment]
You have to go to the folder where pLink is installed. You will find a file labeled modification.ini that you can open up with notepad. My modifications were the very last ones.
