### ISSUE TITLE
pConfig hanging

### ISSUE THREAD

**Issue by PhosPhopeptides** [pFindStudio/pLink2#33]
My pConfig appears to have hung. I cannot access it to edit the LINKER function.

**Comment by 01joy** [comment]
Could you show me the screenshot of your pConfig?

**Comment by PhosPhopeptides** [comment]
I am not able to show you a screen shot. As soon as I click on the Linker tab it comes up with pConfig has stopped working and Windows is investigating why!!!

**Comment by PhosPhopeptides** [comment]
I have now downloaded pLink onto a new pc but the software only runs as far as initializing.
*********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pParse] MS1list completes. 
[pParse] Processing CK_2018-03-05_Auto-C.MS1 
[pParse] CSV file already exists, pParse Complete! 
[pParse]  == == == Time elapsed: 0 seconds. == == == =  
[pLink] Welcome to use pLink v2.3.3, it will be expired on 20190101
[pLink] Search Engine initializing...

**Comment by PhosPhopeptides** [comment]
I have as yet solved this issue.

**Comment by PhosPhopeptides** [comment]
Where do I find the xink.ini file

Regards

Colin

**Comment by 01joy** [comment]
xlink.ini file locates in the pLink2 installation  bin folder.

You can fix the pConfig problem by this way: https://github.com/pFindStudio/pLink2/issues/31#issuecomment-408576365
