### ISSUE TITLE
Filtering of reverse hits

### ISSUE THREAD

**Issue by IwanParf** [pFindStudio/pLink2#36]
Dear pLink 2 developers,
per default reverse hits are filtered from the results files after applying a certain FDR. Is it possible to keep those hits to decoy protein entries by adding a line in the *.plink file somehow, or skip FDR calculation altogether? I would like to test other FDR calculation tools like xiFDR, or xProphet, which is not possible for plink results, if reverse hits are filtered out. 

Best,

Iwan

**Comment by 01joy** [comment]
Dear @IwanParf ,

We keep top-1 match for each spectrum in csv file with the shortest file name. Filter the csv file with column E (Peptide_Type=3 for crosslinked PSM), column N (Target_Decoy=2 for TT, 1 for TD, and 0 for DD), and column Q (Protein_Type=1 for intra and 2 for inter) to calculate different FDRs.

![image](https://user-images.githubusercontent.com/8603895/47284507-3155cb00-d61a-11e8-9b78-f4fd6aa6a4fd.png)
