### ISSUE TITLE
How to find the retention time of the MS1 parent peak for each identified spectra?

### ISSUE THREAD

**Issue by 01joy** [pFindStudio/pLink2#42]
Some users want to know how to find the retention time of the MS1 parent peak for each identified spectra, due to historical reasons, there is no retention time in the pf2 file format, which is the default format used by pLink2. However, mgf does have retention time, so we can find retention time in mgf file.

Use the title of identified PSM to search the mgf file, the `RTINSECONDS` is the retentino time.

![image](https://user-images.githubusercontent.com/8603895/51094980-3a56d280-17ec-11e9-8b46-495b5fd4e409.png)

I made a program called [outputRT.exe](https://github.com/pFindStudio/pLink2/blob/master/files/outputRT.7z?raw=true), you can use it to find the retention time in batch. 

Place all your mgf files in one folder, open command line window in outputRT folder, and type `outputRT.exe mgf_folder_path pLink2_id_path` to run the program, then there will be a `pLink2.RT.csv` generated in the folder of your `pLink2_id_path`.

For example:

![image](https://user-images.githubusercontent.com/8603895/51095619-03cf8680-17f1-11e9-8a94-9d695adc9fa5.png)

If you have trouble in running the `outputRT.exe`, you can install the python 2.7 and run the python script directly.

![image](https://user-images.githubusercontent.com/8603895/51095625-147ffc80-17f1-11e9-9331-918c908dbab5.png)

**Comment by ChengkangLi** [comment]
Hi, it seems like only Windows 8 can run this application file. It does not work in my windows 10.

**Comment by 01joy** [comment]
Dear @ChengkangLi ,

I tested the application file in Windows 10. However, as the exe was packed from python codes, we didn't test it on all Windows system. If you have trouble in running the outputRT.exe, you can install the python 2.7 and run the python script directly.

**Comment by ChengkangLi** [comment]
Dear,
I have Pythan 3.2.2 in my computer, but it does not seem to be worked.

Best regards,
Chengkang

**Comment by 01joy** [comment]
Dear @ChengkangLi ,

Yes, python 3+ is NOT compatible with python 2.7, you have to install python 2.7 to run the script.

**Comment by ChengkangLi** [comment]
Dear,

Thank you very much.

**Comment by ChengkangLi** [comment]
even with python 2.7, it is still not functioning.
