### ISSUE TITLE
How to load pLink2 results to xiNet/xiView?

### ISSUE THREAD

**Issue by 01joy** [pFindStudio/pLink2#43]
Some users want to know how to load pLink2 results to xiNet or xiView, if you know something about it, please help us. Thanks.

**Comment by daheitu** [comment]
A python script can help generate the .csv file required by xiNET. 
https://github.com/daheitu/xiNET_tools

**Comment by 01joy** [comment]
Dear @daheitu , thank you very much for your contribution to the pLink2 community.
