### ISSUE TITLE
stop working

### ISSUE THREAD

**Issue by ColorzhangAmy** [pFindStudio/pLink2#44]
问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	pLink.exe
  问题签名 02:	1.0.0.0
  问题签名 03:	5c3c396b
  问题签名 04:	mscorlib
  问题签名 05:	4.7.3260.0
  问题签名 06:	5bb7bb40
  问题签名 07:	1687
  问题签名 08:	ca
  问题签名 09:	System.IO.FileNotFoundException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	1033
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by 01joy** [comment]
Hi @ColorzhangAmy ,

The error is `System.IO.FileNotFoundException`. I guess some of your file path is invalid or pParse failed to extract the pf2 file.

Please show me the screenshot and parameter file.

**Comment by ColorzhangAmy** [comment]
[stop working.docx](https://github.com/pFindStudio/pLink2/files/2811272/stop.working.docx)

**Comment by ColorzhangAmy** [comment]
[stop working.docx](https://github.com/pFindStudio/pLink2/files/2811273/stop.working.docx)

**Comment by 01joy** [comment]
Hi @ColorzhangAmy ,

Please provide your parameter file with me. Thank you.

**Comment by ColorzhangAmy** [comment]
which one is parameter file, I can't find it.

![default](https://user-images.githubusercontent.com/47165548/51968289-8bcdb580-24ac-11e9-8fc1-bb6ce266d8e6.png)

**Comment by ColorzhangAmy** [comment]
https://pan.baidu.com/s/1QuVc4AWmPb86NbcIUsqWFw
All the files except the raw data. Thank you.

**Comment by ColorzhangAmy** [comment]
The software works well on other computers.
