### ISSUE TITLE
How does the precursor threshold for MARS model works?

### ISSUE THREAD

**Issue by TrahanC** [pFindStudio/pLink2#46]
Where can we find infos on how to setup or how to choose appropriate values for the MARS model threshold, which is set at -0.5 by default? Does this only affect scoring values of the precursors? Is it something that should ALWAYS be left at the default values?

Thanks!

**Comment by 01joy** [comment]
Dear @TrahanC ,

pLink uses pParse to extract and calibrate precursor ions, and pParse uses MARS model to do the work.

General speaking, the higher the MARS score, the more confident the precursor ion. Therefore, if the MARS score threshold is too high, pParse gives fewer precursor ions for pLink to search, which may result in fewer cross-link identifications; if the MARS score threshold is too low, pParse gives more precursor ions for pLink to search, but some extracted precursor ions may be false positive, which may disturb pLink search and take longer time to finish search.

After many performance benchmarks, we find -0.5 a good balance for MARS score threshold. With -0.5, pParse extracts 2~3 precursor ions for each MS2 scans. So, we suggest that you set the parameter as default value, -0.5. Actually, we consider hiding this parameter from GUI in the next version, as the default value -0.5 is the best choice and we don't suggest you to change it.

Here is the homepage of pParse: http://pfind.ict.ac.cn/software/pParse/index.html, which contains information and user guide of pParse.

Thank you for your feedback!
