### ISSUE TITLE
pLabel does not save spectra as pictures in batch mode

### ISSUE THREAD

**Issue by Andreas-MPIbpc** [pFindStudio/pLink2#47]
Dear pLink team,

I guess it is more a pLink1 issue, but, anyway, maybe you can help.
When loading a pLabel file produced by a pLink1 search in combination with the respective mgf files used for the search, pLabel nicely displays and annotates the spectra, but the "Save All Spectra as..." function does not work properly. It goes through all the spectra, also showing a progress bar, but in the end there are no pictures saved. Anyhow, it works for every spectrum individually by clicking "Save Spectra as...", that is somehow annoying for several thousands of spectra. For pLabel files produced by pLink2 everything works nicely.
Do you have any explanation for this, any advice? Maybe it is easy to fix...
Thank you very much in advance!

Best,
Andreas

**Comment by 01joy** [comment]
Dear @Andreas-MPIbpc ,

I tried both pLink1 and pLink2 with their example mgf datasets, the "Save All Spectra as..." function works both for pLink1 and pLink2.

Did you check the correct path set in the "Save All Spectra as..." function? Could you send me your mgf and pLabel files generated by pLink1 and pLink2, so that I can reproduce your problem?

**Comment by Andreas-MPIbpc** [comment]
Dear @01joy ,

thanks for your response! I also tested it with the pLink1 example data set, and it worked. We then focused on the mgf files and it turned out that there were signs within the file names that Windows did not allow (like ;, ", \). After removing them in the mgf- as well as in the pLabel-files saving the spectra in batch mode worked nicely.
So, problem solved.

Thank you!

**Comment by 01joy** [comment]
Dear @Andreas-MPIbpc ,

Thanks for your feedback!

When there are some special characters (such as comma, colon, whitespace etc.) in mgf file name or spectrum title, pLink and pLabel may don't work properly.

So we suggest that the path of file (including raw, mgf, fasta, pLink) doesn't contain any special characters (such as comma, colon, whitespace etc.), and raw file is directly loaded in pLink. As mgf extracted by other tools may not compatible with pLink/pLabel.
