### ISSUE TITLE
pConfig crashes trying to import DB

### ISSUE THREAD

**Issue by Dmorgen** [pFindStudio/pLink2#48]
Hi,

plink is installed in a VM where I have admin rights. the data is imported into local drive, but still crashed when importing DB.

Thanks!
David.

**Comment by 01joy** [comment]
Dear @Dmorgen ,

pLink has not been tested in a VM. From my experience, multithreading is not working in a VM.

Could you show me the screenshot of the crash?

**Comment by Dmorgen** [comment]
Please see:

![image](https://user-images.githubusercontent.com/35773089/54535848-19e7f780-4998-11e9-9b90-8753508476b6.png)

Thanks!
D.

**Comment by 01joy** [comment]
Dear @Dmorgen ,

From your screenshot, we can not tell what's wrong with pConfig. We suggest that you run pLink in a physical machine instead of a VM.
