### ISSUE TITLE
Confident PSMs scored with an e-value of 1

### ISSUE THREAD

**Issue by ThomasGossenreiter** [pFindStudio/pLink2#49]
Dear pLink team,

we are quite confused since we made following observation:

The attached PSM of a BS3 cross-linked peptide seems to be very reliable, but got an e-value of 1. (score 6.65e-003). How can this happen? It does not make a difference which FDR I apply. I even tried it with a 100% FDR applied, since e-values are only calculated for FDR filtered PSMs, right?

Best regards,
Thomas

![PSM](https://user-images.githubusercontent.com/38458148/55167325-0a736600-5171-11e9-8446-584eb750150e.jpg)

**Comment by 01joy** [comment]
Dear @ThomasGossenreiter ,

pLink2 uses SVM scores to estimate FDR, and only calculates E-values for PSMs that pass the FDR threshold. Therefore, change FDR threshold will not change the E-value of this PSM.

The E-value of one PSM equals 1 does not mean this PSM is not reliable, it only means that pLink2 fails to calculate the E-value. As the calculation of E-value requires 5000 background score values, and take the top 10% non-redundant score values to fit a linear model. If the number of top 10% non-redundant score values fewer than 10, pLink2 cannot fit a linear model, thus reports the E-value as 1.

As the E-value calculation requires additional 5,000 background scoring, which was time-consuming. pLink 2 uses the SVM score to rerank PSMs and estimate FDR.

However, SVM scores are flexible for different datasets, so there is no such threshold for SVM scores to determine whether a PSM is reliable or not. The Spectrum_Number >=2 or 3 might be a good indicator for a reliable cross-linked site. The Spectrum_Number of one cross-linked site means how many PSMs supports the cross-linked site. It can be found in the *.filtered_cross-linked_sites.csv file.

For more information about the CSV results, please see [CSV result](https://github.com/pFindStudio/pLink2/wiki/CSV-result).

Thanks for using pLink2.
