### ISSUE TITLE
Retention time information?

### ISSUE THREAD

**Issue by lrschmitt** [pFindStudio/pLink2#50]
I'm wondering if there's a way to have pLink output retention time along with the scan number for each crosslink spectra? I need retention times in order to input my data into Skyline for relative crosslink quantification and so far I've just had to look up retention times manually - which will become more difficult when I have more data. Thanks!

**Comment by 01joy** [comment]
Dear @lrschmitt ,

Please read [this tutorial](https://github.com/pFindStudio/pLink2/issues/42) about how to find the retention time automatically by a script.

**Comment by lrschmitt** [comment]
Thank you! I appreciate the help.
