### ISSUE TITLE
monoisotopic peak

### ISSUE THREAD

**Issue by ThomasGossenreiter** [pFindStudio/pLink2#56]
Dear all,
sometimes cross-linked peptides are quite long and the monoisotopic peak might be below the detection limit. So it could happen that the already corrected precursor mass of pParse might not correspond to the monisotopic peak. Is pLink somehow considering this issue in terms of "blindly" searching for example - 1 and 2 Da precursor masses?

Best regards,
Thomas

**Comment by 01joy** [comment]
Dear Thomas,

No. After pParse, pLink assumes that all calibrated precursor masses are orrect, and only search the small tolerance window ±20ppm around the corrected precursor mass. So, how many of your cases, could you send me some examples, and I will forward it to the pParse team so that they can improve the performance of pParse.

Thank you for your feedback.

**Comment by ThomasGossenreiter** [comment]
Hi,

thanks for your quick reply. So far I was just interested how pLink 2 is handling this, because I remember that for pLink 1 also the isotope peaks were submitted for search. So I just wanted to know if it is the same for pLink 2. In my opinion pParse is doing a really good job. However, I was just wondering if this could be an issue. If I find any cases in the future with this issue, I will of course send it to you.

Thanks a lot!

**Comment by 01joy** [comment]
Dear Thomas,

Thanks for your reminder. From our benchmarks, pParse + small tolerance is better than no pParse + blindly searching -1/+1/+2 Da precursors. There may be some exceptions, but pParse + small tolerance is better in most cases, both for pFind and pLink. Nevertheless, we keep working on pParse, if you find any bug about it, please email it to pparse@ict.ac.cn.

**Comment by ThomasGossenreiter** [comment]
Okay, I would have expected the same as you said. Thank you for your help!
