### ISSUE TITLE
Dead-end reactions (mono-links)

### ISSUE THREAD

**Issue by ThomasGossenreiter** [pFindStudio/pLink2#57]
Dear pLink Team,

is there a way to specify 2 different mono-links for one cross-linker? I am asking as I would like to search hydrolyzed and ammonium quenched BS3 mono-links within one search.

Best regards,
Thomas

**Comment by 01joy** [comment]
Dear Thomas,

I'm sorry that the current version of pLink only supports one mono-links for one cross-linker. Nevertheless, you can set the extra mono-link mass as a variable modification, if there is such a peptide having two mono-links, pLink should find it as a mono-link peptide with the extra variable modification.

**Comment by ThomasGossenreiter** [comment]
Okay, I see. Would it be possible to define two identical cross-linkers, with the only difference in mono-link mass and add both for the database search? Or does pLink then search redundant sequences? This would then lead to redundant identifications and probably also effect FDR. What do you think?

**Comment by 01joy** [comment]
Yes, you can also use two identical cross-linkers with different mono-link masses, pLink will choose one best cross-linker for each spectrum, so this would not lead to redundant identifications.

**Comment by ThomasGossenreiter** [comment]
Dear pLink team,

I tried this now. I defined 2 identical cross-linker with the only difference in the mono-link mass: hydrolyzed: +156.079 and TRIS quenched +259.142 and did 3 database searches: one with each cross-linker and one with both cross-linker defined. I would have expected that I should get the same number of cross-links since the mass of the cross-linker is the same for both cross-linker (+138.068) and I enabled "separate FDR" for all searches. However I do not get the same number of cross-links for each search:
H2O/TRIS/both:
576/544/575 cross-linked spectra
148/127/149 cross-linked peptide pairs
101/87/102 cross-linked sites 

pConfig > Linkers:
![image](https://user-images.githubusercontent.com/38458148/62703207-f37b3500-b9e8-11e9-90c5-5ec7fde3a86e.png)

Do you have any idea what is going on here?
