### ISSUE TITLE
Issue with generating statistics

### ISSUE THREAD

**Issue by AndreLuettig** [pFindStudio/pLink2#58]
When trying to generate a statistical file in pLabel, I get the following error:
![grafik](https://user-images.githubusercontent.com/43988390/61204854-a90adf00-a6ee-11e9-9a4a-dd7bdc5f3996.png)

The resulting txt file is also not complete, some of the scans are missing. Can you help me with this?

**Comment by 01joy** [comment]
Dear @AndreLuettig ,

Could you provide the .plabel and mgf file with me, so that I can reproduce your problem.

**Comment by AndreLuettig** [comment]
Sure, here you go :)
[pLabel_error.zip](https://github.com/pFindStudio/pLink2/files/3405026/pLabel_error.zip)
