### ISSUE TITLE
Weird numbers in precursor_error_distribution.csv

### ISSUE THREAD

**Issue by microdou** [pFindStudio/pLink2#59]
I'm trying to understand the data shown in `reports\precursor_error_distribution.csv`.

Here are the questions:
- **First, what does each column mean?**
The data table is presented without column titles. It looks like the data is sorted by column 3 in descending order. I figured out columns 1 & 2 are `Precursor_Mass_Error(Da)` & `Precursor_Mass_Error(ppm)`, but I couldn't figure out what columns 3-5 mean.

- **Second, some numbers appear to be too large...**
Numbers in column 3 abruptly become as large as **`e+038`** towards the end of the table (_as shown below_), which can be resulted from some calculation bug. If that's the case, I'm concerned that this bug might filter out some positive identifications.

```
-0.01869,   -8.54541, -39.5518,       0, 3
-0.041835, -17.1084,  -39.7004,       1, 3
-0.041589, -10.5107,  -39.89,         1, 3
-0.033696, -10.0624,  -39.9388,       2, 3
 0.030256,  16.337,   -40.204,        1, 3
-0.024363, -14.2231,  -41.0635,       0, 3
 0.06527,   17.4623,   -3.40282e+038, 1, 3
-0.046203, -18.2091,   -3.40282e+038, 1, 3
-0.037315, -14.5916,   -3.40282e+038, 1, 3
-0.027676, -16.8244,   -3.40282e+038, 1, 3
-0.047786, -18.7007,   -3.40282e+038, 2, 3
-0.037989, -11.4851,   -3.40282e+038, 1, 3
-0.036913, -18.3455,   -3.40282e+038, 0, 3
```

**Comment by 01joy** [comment]
Dear @microdou ,

The file `reports\precursor_error_distribution.csv` contains precursor erors for all PSMs, and the file `reports\filtered_precursor_error_distribution.csv` contains only the precursor errors for all `filtered` PSMs. Both files share the same column meanings. They are: `Precursor_Mass_Error(Da)`, `Precursor_Mass_Error(ppm)`, `SVM score`, `Target or Decoy`, and `Peptide Type`. You can find the meaning of these columns in the wiki: https://github.com/pFindStudio/pLink2/wiki/CSV-result.

The SVM score `e+038` just means this PSM is poorly matched, it has lost the meaning as a score. Those PSMs with score `e+038` are most decoy PSMs and have not passed the FDR filter.
