### ISSUE TITLE
NO result shown

### ISSUE THREAD

**Issue by ShenXipeng** [pFindStudio/pLink2#6]
I tryed one sample tody. But one bug shown and I didn't get expected data.
What's the problem?

![default](https://user-images.githubusercontent.com/35022470/34568576-39ec086e-f1a1-11e7-8f0e-8b232a7b0f16.png)
The report also seems right:
Calling pXtract to export MS1 and MS2 files... 
[pParse] MS1list completes. 
[pParse] Processing EnVCD4m-trypsin.MS1 
[pLink] Welcome to use pLink v2.2.1649, it will be expired on 20190101
[pLink] Search Engine initializing...
[pLink] Generating reverse database...
[pLink] Search identifier: TXRQH
[pLink] Search Engine is ready to search.

[pLink] Start searching D:\TemporaryData\14-lumos\EnVCD4m-trypsin_HCDFT.pf2, Labeling None
[pLink] Load File0.Tmp.All.pfd.
[pLink] Start re-ranking using SVM...
[pLink] Iteration: round 1/5
[pLink] Iteration: round 2/5
[pLink] Iteration: round 3/5
[pLink] Iteration: round 4/5
[pLink] Iteration: round 5/5
[pLink] Complete re-rank.

[pLink] Saved Protein sequences for samples 1,4,5 and 6_2018.01.04.File0.pfd.
[pLink] Complete Searching EnVCD4m-trypsin_HCDFT.pf2.

[pLink] Start to generate reports...
[pLink] Complete report.

**Comment by 01joy** [comment]
Hi ShenXipeng,

It seems there is something wrong with **draw.exe**, which draws precursor error distribution and fdr curve. If it works, there will be three images in images folder like below:
![image](https://user-images.githubusercontent.com/8603895/34598720-601bab1a-f229-11e7-9a7f-ac99f6067930.png)

Although draw.exe crashed, the search task was finished completely, you can check out the results in reports folder.

In order to fix this bug, could you open a command line window in pLink2 bin folder, and type draw.exe pLink2_parameter.plink, for example:

![image](https://user-images.githubusercontent.com/8603895/34598991-09323cb8-f22b-11e7-8ffd-28a133974448.png)

then type Enter, post the error information.

**Comment by ShenXipeng** [comment]
all the *.csv files are empty. like below:
![default](https://user-images.githubusercontent.com/35022470/34601312-52e0ab00-f236-11e7-8983-6d2f7961a376.png)

after the command you told me:


![default](https://user-images.githubusercontent.com/35022470/34601272-2ec6d1c2-f236-11e7-9a9f-7a22fce2edcc.png)

**Comment by 01joy** [comment]
Hi ShenXipeng,

It's confusing that all the *.csv files are empty. Could you first try the example dataset come along with pLink2.

The example dataset is located in /pLink2/example/.
![image](https://user-images.githubusercontent.com/8603895/34646021-7352637a-f398-11e7-818b-739984a35555.png)

The  parameters  for  pLink2 search  are as  follows: linker is BS3, enzyme is Trypsin, fixed modification is Carbamidomethyl[C], variable modification is Oxidation[M], all other parameters are default.

Run this example search to see if there are results in *.csv files and if draw.exe works.

**Comment by ShenXipeng** [comment]
I have tryed the samples in plink2 program as you told. succeed! 
Then I tryed to transfer *.raw file to *.mgf rather than load the *.raw directly. succeed!
It seems that I need to transfer the raw file first before searching.
The only problem now is no FDR Curve figure shown. This problem also exist when I use example file for searching.
I really appreciate your help anyway!

**Comment by ShenXipeng** [comment]
another question:
In the first *.csv file, I see a lot of crosslinked peptides, but I can not find it in my *.fasta file. Is that normal?
Shoud I only trust the file in *cross-linked_peptides.csv ?

**Comment by ShenXipeng** [comment]
another question:
In the first *.csv file, I see a lot of crosslinked peptides, but I can not find it in my *.fasta file. Is that normal?
Shoud I only trust the file in *cross-linked_peptides.csv ?

**Comment by 01joy** [comment]
Hi ShenXipeng,

Did you mean pLink2 didn't work with RAW files? Have you correctly installed the MSFileReader according to [the MaxQuant docs](http://www.coxdocs.org/doku.php?id=maxquant:common:download_and_installation#msfilereader)?

Did the FDR curve like below, there was a blue line in the image.
![image](https://user-images.githubusercontent.com/8603895/35090620-2c66dd16-fc75-11e7-9075-3351b47c8d46.png)

For the last question, the first *.csv file in reports folder contains all Top1 results for each spectrum. Some are targets, some are decoys. The column `Target_Decoy` indicates the type of results, 0 for decoy-decoy, 1 for decoy-target, 2 for target-target.

You should only trust results in \*.**filtered_**\*.csv files which have been filtered.

**Comment by ShenXipeng** [comment]
Yes, the FDR curve do like the figure you submitted, there was a blue line in the image. So, to solve the peoblem, I need to reinstall the MSFileReader ?
By the way, what do you mean by saying 0 for **decoy-decoy**, 1 for **decoy-target**, 2 for **target-target**? For example, what's the meaning of decoy-decoy ?

**Comment by 01joy** [comment]
When MSFileReader is installed correctly, the log should be like this, if not, you need to reinstall the MSFileReader.

  \*********************************************
 /       pParse2.0 (x64) from pFind Studio     \
/        Email  :  pfind@ict.ac.cn              \
\        Website:  http://pfind.ict.ac.cn       /
  \*********************************************
[pParse] Calling pXtract to export MS1 and MS2 files...
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract E:\TestData\raw\d\RD_pH_8point3_step5.raw
**[pXtract] pXtract tries to use MSFileReader
[pXtract] : 100.00%
[pXtract] Output Files Completed!**
[pXtract] == == == Time elapsed: 27.088s. == == ==
[pParse] MS1list completes.
[pParse] Processing RD_pH_8point3_step5.MS1
[pParse] Loading MS1 and MS2 files...
[pParse] Loading MS1 Spectra Number: 2143
[pParse] Loading MS2 Spectra Number: 6391
[pParse] Writing MS1 to PF...

[pParse] : 100%

[pParse] Evaluting by the classifier...
[pParse] Filtering by the threshold...

[pParse] : 100%
[pParse] Writing CSV...
[pParse] Releasing resources...
[pParse] Saving CSV to disk...
[pParse] Exported 17218 precursors.
[pParse] Found 0 duplicate scans.
[pParse] == == == Time elapsed: 48 seconds. == == == =
[pLink] Welcome to use pLink v2.2.1649, it will be expired on 20190101
[pLink] Search Engine initializing...


You know one cross-linked peptide consists of two linear peptides linked by a cross-linker, each linear peptide may come from target or decoy protein sequences when searching with forward and reversed protein database, which results in decoy-decoy, decoy-target or target-target forms.

**Comment by ShenXipeng** [comment]
Thanks very much for your patients! 
Best regards
