### ISSUE TITLE
suggestion for possible improvements

### ISSUE THREAD

**Issue by RicZen** [pFindStudio/pLink2#60]
dear developer of plink, 
I would like to add a feature that would be interesting for some crosslinker like a signature peak. The peak could be added (as mass ) in the pConfig and the algorithm could look for it and report it's presence in the final outputs.

**Comment by 01joy** [comment]
Dear @RicZen ,
Thanks for your advice. 

Could you tell us which crosslinker did you use? If it is possible, could you provide us with some sample data, so that we could test this new feature.

**Comment by RicZen** [comment]
hey thank you for your fast answer.

so we use many types of crosslinkers, but I am interested mainly in the noncleavable like DSS or BS3.
you can check one of our group most recent article https://doi.org/10.1016/j.ijms.2019.116184 
there are all the info and raw file in the article.

for DSS, for example, I would like to add 305.22 as signature peak, this way plink should give more confidence in the id.
would it be possible to implement it?

**Comment by 01joy** [comment]
Dear @RicZen ,

As most non-cleavable crosslinkers have no signature peaks, we suggest you can program a preprocess script to pre-filter the spectra which contain customized signature peaks, and then submit to pLink search. If more users request this feature, we will consider to implement it to pLink.

Thanks for your support to pLink.

**Comment by RicZen** [comment]
I am not sure about the other Crosslinkers, but I think DSS and BS3 are some of the most used anyway, and all compounds with similar chemistry will for sure have it. 
other important thing is that DSS has also other peaks for monolinks that would greatly help the id and give a higher certainty. 

in any case, I can prefilter for the spectra with sign peak, but I would get an mgf file and plink doesn't allow me to use them. In any case, an mgf with only the peaks that contain 305.22 (for dss) would only contain crosslinks (no mono or normal peptides) so I think FDR should be taken differently, am I right?

**Comment by 01joy** [comment]
Dear @RicZen ,

pLink supports mgf format, and you can select MGF as the MS Data Format in the MS Data panel, and then add the mgf filtered by the signature peak.

I think the FDR for mgf with only the signature peak is the same as the normal, because pLink does not use the signature peak information.
