### ISSUE TITLE
Not given 32 bit option when installing MSFileReader 3.1 SP2

### ISSUE THREAD

**Issue by mriffle** [pFindStudio/pLink2#62]
Installing MSFileReader 3.1 SP2, I'm never given the 32 bit option and it only installs the 64 bit version. pLink is obviously unhappy about this.

Does anyone know why I might not be getting the 32 bit option?

**Comment by mriffle** [comment]
Reading the FAQ here (https://github.com/pFindStudio/pLink2/wiki/FAQ), it looks as though I have the correct file from thermo but am not being given the option to install the 32-bit version. 

Any idea why?

**Comment by mriffle** [comment]
Should add:

Windows 10 Pro
Version 1903

**Comment by mriffle** [comment]
Also tried on a brand new install of Windows 10 Pro, nothing else installed. Still never got the 32 bit option.

**Comment by mriffle** [comment]
OK, spent time on this and tried installing MSFileReader 3.1 SP2 on the following versions of windows using VMs: 2016 LTSB, 1703, 1709, 1809, and 1903. 

In none of these cases was I ever given a 32-bit option for MSFileReader. I'm a bit at a loss as I do not know how it's possible to install and use pLink 2.3.6 on Windows 10 if MSFileReader can only be installed as 64 bit.

**Comment by mriffle** [comment]
I have now also tried this on Windows 8, and no 32-bit option for MSFileReader is presented.

**Comment by 01joy** [comment]
If pLink works OK with MSFileReader 3.1 SP2 which has only 64-bit option, then there is no need to worry about the missing 32-bit option.

**Comment by mriffle** [comment]
pLink does not work with the 64-bit MSFileReader 3.1 SP2. It complains that it needs the 32 bit version. I will re-try with the 32 bit MSFileReader 3.0 when I get a chance.

**Comment by mriffle** [comment]
OK. I was able to get pLink 2.3.6 to work with MSFileReader 3.0 SP2. It presented a 32-bit option, which I installed (note if I also installed the 64-bit version, pLink would not process RAW files.)

I think you may want to update the official directions, since I'm not sure running pLink with MSFileReader 3.1 SP2 is really possible. I heard from Thermo and they say there is no 32-bit version of MSFileReader 3.1.

**Comment by 01joy** [comment]
OK, thank you @mriffle , and I have updated the tutorial: https://github.com/pFindStudio/pLink2/wiki/FAQ#how-to-install-msfilereader
