### ISSUE TITLE
pLink2 does not complete the task

### ISSUE THREAD

**Issue by CarolCarnielli** [pFindStudio/pLink2#63]
Dear,
I am working with raw data obtained from an Q-Exactive mass spectrometer. I am searching for crosslinking peptides in a sample that was immunoprecipitated from human cell lines. I have submitted the search in pLink2.3.6 against the whole human proteome. Unfortunately it seems not to be working. The total spectra is 67400 and pLlink2 is able to perform the uploading of spectra but then stops and doesn´t move forward. Is there a limitation for the number of spectra? How long does a search like this take in pLink2? Thank you very much. Best Regards

**Comment by 01joy** [comment]
pLink 2 does not limit the number of spectra or protein sequences.

If pLink 2 did not move forward, you should first check whether pLink 2 is working or not. Open the windows task manager, check whether pLink 2 (searcher.exe) occupies CPU and memory. If yes, pLink 2 is working properly, it just needs time to move forward. If pLink 2 (searcher.exe) occupies nearly no CPU or memory, pLink 2 may be down. Please check the spectra or fasta file.

I suggest that you first check your RAW and fasta are OK. Here are two experiments you can do: 1) your fasta + example mgf file to test your fasta is OK; 2) your RAW + example fasta to test your RAW is OK.

If you have passed these two experiments, then you can search with your fasta + your RAW.

**Comment by ChengkangLi** [comment]
what if there is no CPU memory for pLink???

**Comment by 01joy** [comment]
@ChengkangLi If there is no CPU and memory for pLink, it means pLink crashed, and you have to check the log.out file in tmps folder.
