### ISSUE TITLE
Protein names in results are mangled compared to the fasta file

### ISSUE THREAD

**Issue by vladtheimpalerSr** [pFindStudio/pLink2#66]
Previous version of pLink2 displayed the protein names in the results in full. New version cuts them up in random fashion. Example: protein names in fasta file are RpoA, RpoB, RpoC, and RpoZ. In results the names are RpoA, Rpo, Rp, etc. Same fasta files worked just fine with 2019 version.
Used different files, toggled between low and upper case protein names, still the same nonsense. 
![FastaVS](https://user-images.githubusercontent.com/35505821/71846091-bef2ce80-3097-11ea-939c-92561d42aecd.PNG)
![ResultsVS](https://user-images.githubusercontent.com/35505821/71846098-c5814600-3097-11ea-8b88-32eecb57030e.PNG)

**Comment by 01joy** [comment]
Dear @vladtheimpalerSr ,

Thanks for your feedbacks, I am going to fix this bug in this week, and will let you know as soon as possible.

**Comment by 01joy** [comment]
Dear @vladtheimpalerSr ,

I have fixed the bug in version 2.3.9, please download it [here](https://github.com/pFindStudio/pLink2/raw/master/installer/pLink2.3.9.exe) and help me test it. Thank you.

**Comment by vladtheimpalerSr** [comment]
The bug appears to be fixed in 2.3.9 
![photostudio_1578263375543](https://user-images.githubusercontent.com/35505821/71911603-05046c80-3142-11ea-9fe0-556825e2584e.jpg)

**Comment by 01joy** [comment]
Dear @vladtheimpalerSr ,

Thanks for your test and feedback. We officially released the [version 2.3.9](https://github.com/pFindStudio/pLink2#downloads), and all users using version 2.3.8 are recommended to update to version 2.3.9.
