### ISSUE TITLE
Could not open pGlycoDB-GP.txt for writing

### ISSUE THREAD

**Issue by baixue599** [pFindStudio/pLink2#69]
[pGlyco_task_2020-01-19-MS2000022.log](https://github.com/pFindStudio/pLink2/files/4082344/pGlyco_task_2020-01-19-MS2000022.log)

**Comment by 01joy** [comment]
Dear @baixue599 ,

Your path contains chinese characters, please make sure the path contains only alphabets and numbers, no chinese characters, no whitespaces, and other special characters.

`D:\鐢ㄦ埛鏁版嵁\绯栬偨\MS2000022\pGlyco_task_2020-01-19-MS2000022\process1\pGlycoDB-GP.txt`

**Comment by jalew188** [comment]
@baixue599 不同的系统对中文的编码不同，所以目录显示的是乱码，导致目录无法被pGlyco识别，考虑换成英文数字试试。
