### ISSUE TITLE
fail to get the license for pLink2

### ISSUE THREAD

**Issue by yxz98** [pFindStudio/pLink2#71]
Application date: 2020.02.19
User name: zhe yang
University / Company: university of queensland
Work email address: uqzyang3@uq.edu.au
Lab leader / Supervisor: rohan teasdale
Supervisor's email: R.Teasdale@uq.edu.au
Country / Region: Australia
How do you hear about pLink: nature comm paper
What can pLink do for you: crosslinking mass spec
Activation code: 412B6F53FEB467CC449CDF662E49821F

**Comment by 01joy** [comment]
Deear Zhe,

I have sent you the license by email, please check your email inbox.

**Comment by yxz98** [comment]
Thank you!

Cheers,
Zhe Yang

________________________________
发件人: bitJoy <notifications@github.com>
发送时间: 2020年2月19日 20:20
收件人: pFindStudio/pLink2 <pLink2@noreply.github.com>
抄送: yxz98 <yxz98@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [pFindStudio/pLink2] fail to get the license for pLink2 (#71)


Deear Zhe,

I have sent you the license by email, please check your email inbox.

―

**Comment by yxz98** [comment]
Hello, i checked my working email inbox.  However, i could not find license file.  Only email that i can see is below:

The original message was received at Wed, 19 Feb 2020 13:20:48 +1000
from smtp2.soe.uq.edu.au [10.138.113.41]

   ----- Transcript of session follows -----
<plink@ict.ac.cn>... Deferred: Name server: ict.ac.cn.: host name lookup failure
Warning: message still undelivered after 12 hours
Will keep trying until message is 1 week old

Cheers,
Zhe Yang

________________________________
发件人: bitJoy <notifications@github.com>
发送时间: 2020年2月19日 20:20
收件人: pFindStudio/pLink2 <pLink2@noreply.github.com>
抄送: yxz98 <yxz98@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [pFindStudio/pLink2] fail to get the license for pLink2 (#71)


Deear Zhe,

I have sent you the license by email, please check your email inbox.

―

**Comment by 01joy** [comment]
Please provide an alternative email address.

**Comment by yxz98** [comment]
Please send to yxz98@hotmail.com


On 20 Feb 2020, at 7:19 pm, bitJoy <notifications@github.com> wrote:

﻿

Please provide an alternative email address.
