### ISSUE TITLE
require licence 

### ISSUE THREAD

**Issue by parag245** [pFindStudio/pLink2#72]
i just download new version of pLink and send email for new licence but i am not getting any reply.
Application date: 2020.02.18
User name: PARAG GAJJAR
University / Company: BRIGHAM YOUNG UNIVERSITY
Work email address: paraglgajjar@gmail.com
Lab leader / Supervisor: Dr. James Moody
Supervisor's email: jdmoody@chem.byu.edu
Country / Region: United States
How do you hear about pLink: from friend
What can pLink do for you: Mass data analysis
Activation code: DBBF899753BFF8036F2D1F9DBD385494

**Comment by 01joy** [comment]
Dear PARAG GAJJAR,

I have sent you the license by email, please check your email inbox.

**Comment by parag245** [comment]
Thank you very much. Appreciate your help
