### ISSUE TITLE
Email failed to delivery to plink@ict.ac.cn

### ISSUE THREAD

**Issue by yxz98** [pFindStudio/pLink2#73]
Tried to get the licence for pLink2.  But message failed delivery to plink@ict.ac.cn. It was my second-time attempt.  Any helps would be great.

Below is the message from my working place's sever:
**The original message was received at Mon, 24 Feb 2020 09:33:39 +1000
from smtp1.soe.uq.edu.au [10.138.113.40]

   ----- Transcript of session follows -----
<plink@ict.ac.cn>... Deferred: Name server: ict.ac.cn.: host name lookup failure
Warning: message still undelivered after 12 hours
Will keep trying until message is 1 week old_**

My original email is below:

Application date: 2020.02.24
User name: Zhe Yang
University / Company: The University of Queensland
Work email address: z.yang3@uq.edu.au; uqzyang3@uq.edu.au
Lab leader / Supervisor: Rohan Teasdale
Supervisor's email: r.teasdale@uq.edu.au
Country / Region: Australia
How do you hear about pLink: Nature Comm paper
What can pLink do for you: crosslinker identification
Activation code: 412B6F53FEB467CC449CDF662E49821F

**Comment by 01joy** [comment]
Please provide me with an alternative email address.

**Comment by yxz98** [comment]
Please email to: yxz98@hotmail.com directly.

Bests,
Zhe Yang

________________________________
发件人: bitJoy <notifications@github.com>
发送时间: 2020年2月25日 12:26
收件人: pFindStudio/pLink2 <pLink2@noreply.github.com>
抄送: yxz98 <yxz98@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [pFindStudio/pLink2] Email failed to delivery to plink@ict.ac.cn (#73)


Please provide me with an alternative email address.

―

**Comment by 01joy** [comment]
done

**Comment by yxz98** [comment]
I saw your message, but could not see license file here. Did you attach file in this email or send as different email?

Sent from my iPhone

On 1 Mar 2020, at 3:09 pm, bitJoy <notifications@github.com> wrote:

﻿

done

**Comment by yxz98** [comment]
i still could not find license file on my previous email address nominated.  Would you be able to send it again to my different email - zyang0084@gmail.com
Thanks
