### ISSUE TITLE
request for license

### ISSUE THREAD

**Issue by Jianqiao-Shen** [pFindStudio/pLink2#78]
I sent the email for the license but no reply. Below is the required information. Would you please send it to me? Thank you!
Application date: 2020.07.28
User name: Jianqiao Shen
University / Company: University of Waterloo
Work email address: j26shen@uwaterloo.ca
Lab leader / Supervisor: Bin Ma
Supervisor's email: binma@uwaterloo.ca
Country / Region: Canada
How do you hear about pLink: Colleagues in the same lab.
What can pLink do for you: Identify the disulfide bond.
Activation code: C34E1A5B333828E43E7EC7609E3A688B

**Comment by 01joy** [comment]
Dear Jianqiao,


Please find the attached license file for you.


Please open pLink 2 and click "Import the license file" button, browse and import the license, after that, restart pLink 2.


Please cite the paper of pLink 2 (https://www.nature.com/articles/s41467-019-11337-z) if you use results obtained from pLink 2.


You can contact us by email (plink@ict.ac.cn) or leave a message in pLink 2 repository (https://github.com/pFindStudio/pLink2/issues). Any comments, questions, and bug reports are welcome. Please see&nbsp;github.pdf&nbsp;for GitHub usage.


Thanks for your support to pLink 2!



-Zhenlin




Best regards,
The pLink Team of pFind Lab
Institute of Computing Technology
Chinese Academy of Sciences
plink@ict.ac.cn
http://pfind.ict.ac.cn



&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by 01joy** [comment]
[j26shen@uwaterloo.ca.pLink.zip](https://github.com/pFindStudio/pLink2/files/4998581/j26shen%40uwaterloo.ca.pLink.zip)

I did not receive your license maybe it was spamed. Please see the license.

**Comment by Jianqiao-Shen** [comment]
Got it. Thank you for your help.
