### ISSUE TITLE
How to select modifications as fast as possible?

### ISSUE THREAD

**Issue by 01joy** [pFindStudio/pLink2#79]

**Comment by NorthblueM** [comment]
Type the prefix index to quickly locate your target modification: 
1. Put your cursor in the modifications list. Select any of the options.
2. Type the prefix of your target modification to quickly locate the target. (Enter by keyboard.)
3. Select your target option.

Please look at the following GIF.

![select_modification_fastly](https://user-images.githubusercontent.com/45622011/93982128-6f823900-fdb3-11ea-8b36-9ecee286aa28.gif)
