### ISSUE TITLE
browsing through spectra with plabel does not work

### ISSUE THREAD

**Issue by IwanParf** [pFindStudio/pLink2#8]
After loading a plabel file into plabel one sees the first spectrum, but when browsing through them the spectrum does not change, only annotation changes if it fits to a peak. browsing through mgf files works though, but annotation is obviously missing.

**Comment by 01joy** [comment]
Hi IwanParf,

You can scroll up or down or click the left and right arrow in top right corner in pLabel to browsing different spectra.

![image](https://user-images.githubusercontent.com/8603895/34646071-cf5d1286-f399-11e7-843d-77d6c9530f96.png)

Click All will show all spectra, then select the spectra you want to see.

![image](https://user-images.githubusercontent.com/8603895/34646077-00035558-f39a-11e7-9440-c64067853d3b.png)

pLabel won't show annotation when opened with mgf files, as mgf only has peak information, it has no peptide information, as a result, pLabel can't annotate the peak-ion match.

**Comment by IwanParf** [comment]
Thank you for the response. My point is that exactly these arrows do not change the spectrum when clicked.

**Comment by 01joy** [comment]
Hi IwanParf,

I recently found another user also had this problem, it had something to do with the mgf format.

Could you provide me with the mgf and *.plabel file so that I can reproduce your problem?

**Comment by IwanParf** [comment]
Hello 01Joy,
apparently you are right with the mgf format. It works for me with searches, for which I provided raw files, but not when I provide mgf files. I did mgf conversion with Proteome Discoverer 2.1


[IParfentev_020216_Xlink_Fract_A56_A12.zip](https://github.com/pFindStudio/pLink2/files/1618145/IParfentev_020216_Xlink_Fract_A56_A12.zip)

**Comment by 01joy** [comment]
Hi @IwanParf ,

I finally found the problem. As spectrum title in MGF extracted by PD contains many punctuations, such as whitespace, comma, quotes, equal sign, which results in a minor bug in generating *.plabel files.

I have fixed this bug, the new version will be released at the end of this month.

**Comment by 01joy** [comment]
Hi @IwanParf  ,

This bug has been solved in pLink 2.3.0, which is released on January 31, 2018, please goto http://pfind.ict.ac.cn/software/pLink/index.html#Downloads to download the new version and try again.

Thanks for your feedback.
