### ISSUE TITLE
Pfind can't add new modification 

### ISSUE THREAD

**Issue by labguyatscripps** [pFindStudio/pLink2#82]
Hi 
I tired to add a new modification for Pfind search. My modification composition is C(3)F(3)O(1)H(1). I got stuck after I added C(3). There is no step that I can continue to add the rest of formula F(3)O(1)H(1). 
Any advice? Thanks.

**Comment by 01joy** [comment]
Hi,

After you add C(3), select the element `F` from the list and click the `+` button. After that, select the element `O` and repeat the procedure like below:
![image](https://user-images.githubusercontent.com/8603895/106837525-9e030f80-66d5-11eb-9d99-7d3223d90f1d.png)

**Comment by labguyatscripps** [comment]
I found the solution. Thank you for your reply.
With best regards,
Ming

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
