### ISSUE TITLE
no enough spaces to infer proteins

### ISSUE THREAD

**Issue by pursuream** [pFindStudio/pLink2#89]
Dear pLink team,

In my pLink search, the system said:
"there are no enough spaces to infer proteins, try to allocate new spaces (6.10MB).
there are no enough spaces to infer proteins, try to allocate new spaces (12.21MB).
there are no enough spaces to infer proteins, try to allocate new spaces (24.41MB)."
but the re-ranking program started without asking me for any operation.

What dose this mean? What can I do to improve the results? 

Thanks!
![捕获6](https://user-images.githubusercontent.com/84061096/117921169-d6dd0100-b322-11eb-844e-629e83aef4b9.PNG)

**Comment by 01joy** [comment]
Dear @pursuream ,

This information means that pLink will allocate more computer memory to infer proteins. It's a normal phenomenon. No more actions are required. Just ignore it.
