### ISSUE TITLE
metadata configuration

### ISSUE THREAD

**Issue by IwanParf** [pFindStudio/pLink2#9]
Hello plink team,
Thank you for the new software! I found an interesting bug:
the numbers, ie masses of amino acids, linkers etc., are apparently in mDa and the decimal point is a comma. It looks weird, but it is not an issue; searches are working and the .ini files in \bin are correctly in Da and with a period. If one now adds e.g. a new linker over the metadata configuration option within the program, it kind of overwrites the .ini files in the \bin with the weird formatting (commata and in mDa), which basically leads to no identified spectra at all. One has to reinstall the program to get back the correct .ini file. The "Region and Language" format option on my computer is in English (United States) and the decimal symbol is a period.

**Comment by IwanParf** [comment]
Another thing:
If one wants to define another amino acid (e.g. B for some kind of substitution) and clicks on save, it does not save and the asterisk at the name of the tab in the metadata config (e.g. Databases, Linkers, Sumoes etc.), which usually indicates a change, is at the Enzymes tab.

**Comment by 01joy** [comment]
Hi IwanParf,

The bugs you have found are interesting, thanks a lot!

For the first bug, I think it has something to do with the software globalization, as the decimal point in China is a period but in Germany is a comma. So could you tell me your windows version and the language of your windows so that I can reproduce your problem?

For the second bug, it's about pConfig.

Thanks for using pLink2, we will fix these bugs in the next version.

**Comment by IwanParf** [comment]
Dear pLink team,
I am running plink 2 on Windows 7, Service pack 1, 64 bit. Language is English and I have changed the decimal point to a period in the system's settings manually (usually any other MS software has also issues otherwise).

**Comment by 01joy** [comment]
Hi @IwanParf ,

As for the decimal point problem,  I have fixed it as period in different cultures. So this problem is solved.
The pConfig problem has also been solved.

New version of pLink2 will be released at the end of this month. Please stay tuned for it.

**Comment by 01joy** [comment]
Hi @IwanParf  ,

This bug has been solved in pLink 2.3.0, which is released on January 31, 2018, please goto http://pfind.ict.ac.cn/software/pLink/index.html#Downloads to download the new version and try again.

Thanks for your feedback.
