### ISSUE TITLE
option for cleavable crosslinker not in dropdown menu

### ISSUE THREAD

**Issue by FraenzeMueller** [pFindStudio/pLink2#91]
Dear plink-Team,

I am using plink2 v. 2.3.10 at the moment and wanted to start a crosslink search with DSSO. As DSSO is not predefined, I went to the "Meta Data Configuration" tab and added DSSO. After saving, I wanted to select DSSO from the dropdown menu in the identification tab but the only choice I have is "Conventional Crosslinking" and "Disulfide Bond". DSSO is not appearing in both lists. I know from v 2.3.9 that there was also an option for cleavable crosslinker but its gone in the new version. Would it be possible to add it again? Or is there a work around?

Best wishes

**Comment by NorthblueM** [comment]
Dear @FraenzeMueller,

For DSSO, pLink v2.3.9 only support MS2(CID+ETD), and has not been systematically evaluated on various data sets. We hope the flow that are open to users are reliable, so we close the DSSO flow temporarily. We are developing new DSSO flow for MS2-SteppedHCD with better performance, which will open up in the near future. If you want to use the old DSSO flow, pLink v2.3.9 is still available.

Best Regards
